### PR TITLE
Proposed fix for dependency handling.

### PR DESCRIPTION
**Pull request by Elland**

### CODE REVIEW

**Comment by 3lvis** [comment]
So they are only used for the Demo project? If they are meant to be sub-dependencies they should be in "Cartfile". "Cartfile.private" is only for internal (demo project) dependencies.

**Comment by Elland** [comment]
So how do we deal with it being included twice of your app also depends on those frameworks?

**Comment by 3lvis** [comment]
We need to find a way to fix it, meanwhile, I guess is fine to merge this.

**Comment by 3lvis** [comment]
We might need to add a warning to the README.

**Comment by Elland** [comment]
What we have in place works for now. I'd rather merge a proper solution. 😄

**Pull request merged**
